### ISSUE TITLE
Can display the game and let us watch the agent playing it ?

### ISSUE THREAD

**Issue by Shawn617** [Grzego/async-rl#4]

**Comment by Grzego** [comment]
Hi @Shawn617,

I'm not sure if I understand you correctly. Do you want to see how agent is playing?

If so, this should be possible by running this line (in case of `Breakout-v0`):
```
python play.py --model=model-file.h5 --game=Breakout-v0
```
where `model-file.h5` is a file with saved weights which you can get from `sample-weights` directory or by training the model by yourself.

As mentioned in issue #3 there might be some problems with weights in `sample-weights`. However you should be able to use them by limiting the size of action space to 4.

I hope this helps :)
